create table product (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(255),
    price float(53) not null,
    category varchar(255),
    image_url varchar(255),
    stock integer default 0
);

create table users (
    id bigint generated by default as identity primary key,
    username varchar(255) unique,
    password varchar(255),
    role varchar(255)
);

create table cart (
    id bigint generated by default as identity primary key,
    username varchar(255)
);

create table cart_item (
    id bigint generated by default as identity primary key,
    quantity integer not null,
    product_id bigint,
    cart_id bigint,
    constraint fk_cart_item_product foreign key (product_id) references product(id),
    constraint fk_cart_item_cart foreign key (cart_id) references cart(id)
);

create table orders (
    id bigint generated by default as identity primary key,
    username varchar(255),
    total_amount float(53),
    payment_status varchar(255)
);

create table order_item (
    id bigint generated by default as identity primary key,
    quantity integer not null,
    price float(53),
    product_id bigint,
    order_id bigint,
    constraint fk_order_item_product foreign key (product_id) references product(id),
    constraint fk_order_item_order foreign key (order_id) references orders(id)
);

create table payment (
    id bigint generated by default as identity primary key,
    order_id varchar(255),
    payment_id varchar(255),
    status varchar(255),
    amount float(53)
);
