CREATE TABLE wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE wishlist_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    wishlist_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    CONSTRAINT fk_wishlist_item_wishlist
        FOREIGN KEY (wishlist_id)
        REFERENCES wishlist(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_wishlist_item_product
        FOREIGN KEY (product_id)
        REFERENCES product(id)
        ON DELETE CASCADE
);